:concurrency: 5
:verbose: true
:timeout: 50
:queues:
  - searchkick
  - indexer
  - carrierwave
  - default
  - mailers
staging:
  concurrency: 10
production:
  concurrency: 20
logfile: ./log/sidekiq.log